on:
  workflow_dispatch:

jobs:
  sdist:
    runs-on: ubuntu-20.04
    steps:
    - name: clone repo
      uses: actions/checkout@v4

    - name: build sdist
      run: |
        rm -rf dist/
        python -m pip install build
        python -m build --sdist

    - name: upload sdist artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist
        if-no-files-found: error

  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - spec: cp312-musllinux_aarch64
          foreign_arch: true
          test_args: '{project}/src/c'

    steps:
    - name: clone repo
      uses: actions/checkout@v4

    - name: configure docker foreign arch support
      uses: docker/setup-qemu-action@v3
      if: ${{ matrix.foreign_arch || false }}

    - name: build/test wheels
      env:
        CFLAGS: -Dffi_call=cffistatic_ffi_call  # override name for ffi_call to break hard if we linked against someone else's libffi
        CIBW_ARCHS_LINUX: all
        CIBW_BUILD: ${{ matrix.spec }}
        CIBW_BEFORE_BUILD: |
          set -eux && \
          curl -L -O https://github.com/libffi/libffi/archive/v3.4.2.tar.gz && \
          tar zxf v3.4.2.tar.gz && cd libffi-3.4.2 && \
          ./autogen.sh && \
          ./configure --without-gcc-arch --disable-docs --with-pic --enable-shared=no && \
          make && \
          make install && \
          ldconfig || true
        CIBW_ENVIRONMENT_PASS_LINUX: CFLAGS  # ensure that the build container can see our overridden build config
        CIBW_PRERELEASE_PYTHONS: 'True'
        CIBW_TEST_REQUIRES: pytest setuptools  # 3.12+ no longer includes distutils, just always ensure setuptools is present
        CIBW_TEST_COMMAND: PYTHONUNBUFFERED=1 python -m pytest ${{ matrix.test_args || '{project}' }}  # default to test all
      run: |
        python -m pip install --upgrade cibuildwheel

        # actually build libffi + wheel (using env tweaks above)
        python -m cibuildwheel --output-dir dist .


    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: dist
        if-no-files-found: error

  check:
    if: always()
    needs:
    - sdist
    - linux
    runs-on: ubuntu-latest
    steps:
    - name: Verify all previous jobs succeeded (provides a single check to sample for gating purposes)
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
